# Generated by Django 4.1.3 on 2024-04-20 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_request_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
