# Generated by Django 4.1.3 on 2024-05-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_request_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'private chat'), (1, 'group chat')])),
                ('members', models.ManyToManyField(related_name='conversations', to='chat.userinfo')),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.CreateModel(
            name='ReadMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fro', models.IntegerField()),
                ('to', models.IntegerField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_messages', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_messages', to='chat.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('receivers', models.ManyToManyField(related_name='received_messages', to='chat.userinfo')),
                ('reply_by', models.ManyToManyField(blank=True, null=True, related_name='replies', to='chat.message')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chat.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='chat.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DeletedMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted', models.ManyToManyField(blank=True, related_name='deleted_messages', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_messages', to='chat.userinfo', unique=True)),
            ],
        ),
    ]
