# Generated by Django 4.1.3 on 2024-05-05 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_alter_request_timestamp_readmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedmessage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_messages', to='chat.userinfo'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_by',
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_to',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_by',
            field=models.IntegerField(default=0),
        ),
    ]
