# Generated by Django 4.1.3 on 2024-05-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_deletedmessage_user_remove_message_reply_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readmessage',
            name='fro',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='readmessage',
            name='to',
            field=models.IntegerField(default=-1),
        ),
    ]
