# Generated by Django 4.1.3 on 2024-05-06 15:06

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_readmessage_fro_alter_readmessage_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=models.SET(chat.models.get_sentinel_user), related_name='sent_messages', to='chat.userinfo'),
        ),
        migrations.AlterField(
            model_name='readmessage',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(chat.models.get_sentinel_user), related_name='read_messages', to='chat.userinfo'),
        ),
        migrations.AlterField(
            model_name='request',
            name='receiver',
            field=models.ForeignKey(on_delete=models.SET(chat.models.get_sentinel_user), related_name='received_requests', to='chat.userinfo'),
        ),
        migrations.AlterField(
            model_name='request',
            name='sender',
            field=models.ForeignKey(on_delete=models.SET(chat.models.get_sentinel_user), related_name='sent_requests', to='chat.userinfo'),
        ),
    ]
