# Generated by Django 4.1.3 on 2024-05-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_sender_alter_readmessage_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receivers',
        ),
    ]
