# Generated by Django 4.1.3 on 2024-05-12 12:58

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_message_receivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notice',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='chat.conversation')),
                ('manager', models.ManyToManyField(blank=True, related_name='group_manager', to='chat.userinfo')),
                ('master', models.ForeignKey(on_delete=models.SET(chat.models.get_sentinel_user), related_name='group_master', to='chat.userinfo')),
                ('notice', models.ManyToManyField(blank=True, related_name='group', to='chat.message')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.group'),
        ),
    ]
