# Generated by Django 4.1.3 on 2024-05-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_request_managers_alter_request_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='managers',
        ),
    ]
